### PR TITLE
Add Scala 3.0.0 support

### PR DESCRIPTION
**Pull request by grzegorz-bielski**
Added Scala 3.0.0 support, also some `.gitignore` rules for metals, and removed the deprecated `sbt-dotty plugin`.

### CODE REVIEW

**Comment by grzegorz-bielski** [comment]
@travisbrown Could you please approve the run of the GH actions workflow? 🙇

**Comment by grzegorz-bielski** [comment]
@travisbrown Sorry, now it should work... https://github.com/grzegorz-bielski/circe-yaml/commit/297d475852c7f083bba4802fdfa7299b5e002a2e 
Please accept the run again 🙏

**Comment by grzegorz-bielski** [comment]
@travisbrown Are there any blockers for merging this?

**Comment by travisbrown** [comment]
Nope, looks good to me, thanks!

**Pull request merged**
