### PR TITLE
Fixed code coverage by aggregating project coverage.

### PR DESCRIPTION
**Pull request by jeffmay**
@jeremyrsmith @travisbrown 

Fixed the project so that it actually runs the unit tests (no wonder code coverage was 0%).

### CODE REVIEW

**Comment by jeffmay** [comment]
retest this please

**Comment by jeffmay** [comment]
Turns out that the tests fail with Scala 2.10. Interesting...

**Comment by jeffmay** [comment]
@travisbrown any idea why this would only fail in Scala 2.10?
```
- snake.printer.printer.roundTrip *** FAILED ***
[info]   GeneratorDrivenPropertyCheckFailedException was thrown during property evaluation.
[info]    (Discipline.scala:14)
[info]     Falsified after 6 successful property evaluations.
[info]     Location: (Discipline.scala:14)
[info]     Occurred when passed generated values (
[info]       arg0 = {
[info]     "" : {
[info]       "" : 4.879387571923965E+43
[info]     }
[info]   } // 17 shrinks
[info]     )
[info]     Label of failing property:
[info]       (None ?== Some({
[info]     "" : {
[info]       "" : 4.879387571923965E+43
[info]     }
[info]   })) failed
```

**Comment by jeffmay** [comment]
@travisbrown I think I found the issue:

In BiggerDecimal:
```
/**
   * Is a string representing an integral value a valid [[scala.Long]]?
   *
   * Note that this method assumes that the input is a valid integral JSON
   * number string (e.g. that it does have leading zeros).
   */
  def integralIsValidLong(s: String): Boolean = {
    val bound = if (s.charAt(0) == '-') MinLongString else MaxLongString

    s.length < bound.length || (s.length == bound.length && s.compareTo(bound) <= 0)
  }
```

The problem is that it is comparing the length of strings "-2147483649e190" and "-9223372036854775808" and determining that "-2147483649e190" is shorter, and therefore is a valid Long, but it really should not be a `Long`, it should be a BigInt.

**Comment by jeffmay** [comment]
Also, the test fails in both Scala 2.10 and 2.11

**Comment by travisbrown** [comment]
@jeffmay Hmm, that's bad. I thought things were arranged such that that check won't happen if there's an exponent. Taking a look now…

**Comment by jeffmay** [comment]
I was able to fix it by using the `BiggerDecimal.fromString` method, which handles the `'e'` case explicitly.

**Comment by travisbrown** [comment]
@jeffmay It looks like this is a bug in circe-yaml [here](https://github.com/circe/circe-yaml/blob/master/snake/src/main/scala/io/circe/yaml/snake/CirceJsonConstructor.scala#L47). The `fromIntegralStringUnsafe` documentation doesn't make this very clear, but it should only be called when the string has already been validated and the fact that it doesn't contain `e` or `.` has been confirmed.

This is the case with Jawn's `jint` callback, etc., but apparently not for Snake's `Tag.INT`.

An easy fix would be to use the `fromDecimalStringUnsafe` version everywhere, or you could check for `e` / `E` and choose which one to use.

Oh, just saw your comment. Right, `BiggerDecimal.fromString` would work as well, although it's not as lazy, and doesn't use the cheaper representation on small (i.e. `Long`-sized) integers.

**Comment by travisbrown** [comment]
…I'll also get some better documentation in place for `fromDecimalStringUnsafe`.

**Comment by jeffmay** [comment]
So if I check for `'e' | 'E' | '.'` and find it, I should use `BiggerDecimal.fromDecimalStringUnsafe`? And otherwise, `BiggerDecimal.fromIntegralStringUnsafe`?

**Comment by travisbrown** [comment]
Well, I don't know anything about Snake, but I'd assume if you get a `Tag.INT` it's guaranteed not to contain `.`.

This is all just about optimization, so it'd be reasonable just to go the simple route. Jawn was the first parser I integrated, and it provided `jint` with the no-exponent, no-decimal guarantee, so I figured circe might as well be able to avoid re-processing. But it's unlikely to matter most of the time.

**Comment by jeffmay** [comment]
The tag is set explicitly by the printer in the YAML output, so it could be wrong when parsing it. I'm just ignoring whether it is an `Int` or `Float` and just parsing it correctly based on whether it contains a '.' or 'e'.

**Comment by jeffmay** [comment]
We've got better coverage now: https://codecov.io/gh/circe/circe-yaml/branch/fix-coverage

**Pull request merged**
