### PR TITLE
Crosscompile for JS and Native with scala-yaml as the backend

### PR DESCRIPTION
**Pull request by sideeffffect**
This is rudimentary support for YAML on JS and Native. We could add much more tests etc., and maybe there are some bugs for edge cases, but this should be fine for the beginning.

Still Scala Native 0.4.x:
 * https://github.com/circe/circe/pull/2254
 * https://github.com/VirtusLab/scala-yaml/pull/284

### CODE REVIEW

**Comment by armanbilge** [comment]
> This is rudimentary support for YAML on JS and Native.

See discussions in https://github.com/circe/circe-yaml/issues/186 and https://github.com/circe/circe-yaml/issues/285.

I have already published a library based on the scala-yaml backend and I would be happy to move it to the Circe org. I do not recommend mixing multiple backends in the same repository because that creates issues with versioning and compatibility.

https://github.com/armanbilge/scala-yaml

**Comment by sideeffffect** [comment]
I think this is fine, making a new repository is not worth it.
We can make further improvements in the scala-yaml backend after the PR is merged.

**Comment by sideeffffect** [comment]
Pending bugfix https://github.com/VirtusLab/scala-yaml/pull/299

**Comment by sideeffffect** [comment]
Now blocked on
 * https://github.com/circe/circe/pull/2254

**Review by zarthross — APPROVED** [review]

**Comment by OndrejSpanel** [comment]
Great to see effort in this direction. It will be great to have a cross platform support.

How would I test 0.15.3, both on JVM and JS? The artifacts are not present in maven (yet?)

**Comment by sideeffffect** [comment]
The artifacts are already available:
https://repo1.maven.org/maven2/io/circe/circe-yaml-scalayaml_sjs1_3/0.15.3/
https://index.scala-lang.org/circe/circe-yaml/artifacts/circe-yaml-scalayaml

Give them a spin :wink:

**Comment by OndrejSpanel** [comment]
I did not expect a different library name, but it makes sense - and certainly allows me testing.

**Pull request merged**
