### PR TITLE
Parse integers using SnakeYAML's parser

### LINKED ISSUE #41: Non-decimal integer types not parsed correctly
The YAML spec for the `int` tag allows hex, binary, octal and sexagesimal in addition to decimal numbers: http://yaml.org/type/int.html

circe-yaml fails to parse the following valid YAML:

```yaml
number: 0xFF
```
with the error `io.circe.ParsingFailure: Invalid numeric string 0xFF`

I think it would make sense to parse that YAML as equivalent to the JSON document `{"number": 255}`.

### PR DESCRIPTION
**Pull request by nornagon**
Fixes #41

The round-trip test is still occasionally choking on inputs like `-0` and
`0e12356`, which I'm not quite sure how to fix yet, but I thought I'd get this
PR up in case it's helpful.

### CODE REVIEW

**Comment by nornagon** [comment]
I've updated the PR to only change parsing of integers that start with `0x` or contain `_`, neither of which cases circe handles currently. I've left the printer unchanged and continue to use the existing parser for all other integers, since the round-trip tester insists on producing values like `0E+1234` as integers.

**Comment by travisbrown** [comment]
Sorry for the long delay, but this looks reasonable to me (although I think we'll need some `.right` calls for 2.11). @jeremyrsmith, are you okay with this?

**Comment by jeremyrsmith** [comment]
It's OK with me. Like @travisbrown mentioned, it needs right projections (or `import cats.syntax.either._`) for Scala 2.11 in order to pass CI.

**Comment by travisbrown** [comment]
We've dropped 2.11 support and I've just resolved the conflict, will merge when green.

**Comment by nornagon** [comment]
🎉 Thanks for getting to this @travisbrown !

**Pull request merged**
