### PR TITLE
Upgrade to circe 0.12.3

### PR DESCRIPTION
**Pull request by Daenyth**
Ref #86 

- Drop scala 2.11
- Upgrade 2.12 to 2.12.10

### CODE REVIEW

**Comment by Daenyth** [comment]
It looks like the build is failing because travis is using the yml from master branch, I think

**Comment by travisbrown** [comment]
I've never seen that before, and my guess is it's something to do with the config before the force push? I just tried restarting the whole build—if that doesn't work can you try opening a new PR with this branch?

**Comment by Daenyth** [comment]
Weird. I amended the commit and pushed again, now it seems to be building properly

**Comment by travisbrown** [comment]
:+1: from me.

**Pull request merged**
