### PR TITLE
Backport/0.10.x

### PR DESCRIPTION
**Pull request by msilvestre**
Backport integer parser bug fixing.

I couldn't compile and test this, because I'm having this error:

sbt.librarymanagement.ResolveException: unresolved dependency: org.scalastyle#scalastyle-sbt-plugin;1.0.0: not found

Can you please check it?

### CODE REVIEW

**Comment by travisbrown** [comment]
Can you check your sbt install? I can build this branch locally and run tests just fine (although there are test failures I can't look into right now).

**Comment by msilvestre** [comment]
~/P/f/circe-yaml ❯❯❯ sbt --version  
backport/0.10.x:cherry-pick 
[info] 1.2.8
sbt script version: 1.3.3

**Comment by travisbrown** [comment]
I don't really know what could be going on on your system and won't have time to help debug today, but this isn't something that looks familiar to me. You could try updating to sbt 1.3 in this branch?

**Comment by msilvestre** [comment]
I managed to run it locally and fixed the tests

**Comment by msilvestre** [comment]
The integration is failing doing: 

Expected feature release number in range of 9 to 15, but got: 8

The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .

**Comment by travisbrown** [comment]
Can you change the Travis CI config to match master? They’ve dropped some support recently.

**Comment by travisbrown** [comment]
I can take it from here, thanks!

**Pull request merged**
